export const REGISTER_SUCCESS = 'REGISTER_SUCCES';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const FECTH_CHARITY_SUCCESS = 'FECTH_CHARITY_SUCCESS';
export const FECTH_CHARITY_FAIL = 'FECTH_CHARITY_FAIL';
export const CREATE_CHARITY_SUCCESS = 'CREATE_CHARITY_SUCCESS';
export const FETCH_CHARITYBYUSER_SUCCESS = 'FETCH_CHARITYBYUSER_SUCCESS';
export const FETCH_CHARITYBYUSER_FAIL = 'FETCH_CHARITYBYUSER_FAIL';
export const DELETE_CHARITY = 'DELETE_CHARITY';
export const FETCH_CHARITYBYSLUG = 'FETCH_CHARITYBYSLUG';

export const FETCH_PAYMENT = 'FETCH_PAYMENT';
export const CREATE_PAYMENT = 'CREATE_PAYMENT';
export const PUT_PAYMENT = 'PUT_PAYMENT';
export const GET_PAYMENTBYSLUG = 'GET_PAYMENTBYSLUG';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
